# Generated by Django 5.1.6 on 2025-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.FileField(upload_to='data'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
