# Generated by Django 5.1.6 on 2025-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_alter_post_author_alter_post_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.FileField(upload_to=''),
        ),
    ]
